name: 'Pull request: Run unit test'

on:
  pull_request:
    branches:
      - dev
      - master
      - beta

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test  -v -coverpkg ./src/internal/... -coverprofile coverage.out -covermode count ./src/internal/...
          go tool cover -func="./coverage.out"
